/* ── Source catalog (W1.7) ────────────────────────────────────────────────────
 * The systems of record this brain knows — catalogued, not copied. Renders
 * app/sources.json as a tree: source → entity → field, each with status,
 * owner and provenance where declared. The brain holds the catalog; the rows
 * stay in the source.
 */
(function (global) {
  'use strict';
  var esc = function (s) { return global.KBShell.esc(s); };
  var fetchJson = function (u, f) { return global.KBShell.fetchJson(u, f); };

  function meta(o) {
    var bits = [];
    if (o.kind) bits.push(o.kind);
    if (o.type) bits.push(o.type + (o.nullable === false ? ' not null' : ''));
    if (o.is_pk) bits.push('pk');
    if (o.status) bits.push(o.status);
    if (o.owner) bits.push('owner: ' + o.owner);
    if (o.provenance) bits.push(typeof o.provenance === 'string' ? o.provenance : 'provenance');
    return bits.length ? '<span class="ks-tree-meta">' + esc(bits.join(' · ')) + '</span>' : '';
  }

  function field(f) { return '<li><span class="ks-tree-name">' + esc(f.name || f.title) + '</span>' + meta(f) + '</li>'; }
  function entity(e) {
    var fields = e.fields || [];
    return '<li><span class="ks-tree-name ks-toggle" data-toggle>' + esc(e.title || e.name) + '</span>' + meta(e) +
      (fields.length ? '<ul hidden>' + fields.map(field).join('') + '</ul>' : '') + '</li>';
  }
  function source(s) {
    var ents = s.entities || [];
    return '<li><span class="ks-tree-name ks-toggle open" data-toggle>' + esc(s.title || s.id) + '</span>' + meta(s) +
      '<span class="ks-tree-meta">' + ents.length + ' entities</span>' +
      (ents.length ? '<ul>' + ents.map(entity).join('') + '</ul>' : '') + '</li>';
  }

  function mount(host) {
    global.KBShell.mount({ title: 'Catalog' }).then(function () {
      return fetchJson('/app/sources.json', null);
    }).then(function (data) {
      var list = (data && data.sources) || [];
      if (!list.length) {
        host.innerHTML = '<div class="ks-state"><div class="ks-state-title">No sources catalogued</div><div>Declare sources under <span class="ks-mono">generators.sources</span> and run <span class="ks-mono">make sources</span>.</div></div>';
        return;
      }
      host.innerHTML = '<ul class="ks-tree">' + list.map(source).join('') + '</ul>' +
        '<p class="ks-note">' + esc(list.length) + ' sources · generated by ' + esc((data && data.generated_by) || '?') + '</p>';
      host.addEventListener('click', function (e) {
        var t = e.target.closest('[data-toggle]'); if (!t) return;
        var ul = t.parentElement.querySelector(':scope > ul'); if (!ul) return;
        ul.hidden = !ul.hidden; t.classList.toggle('open', !ul.hidden);
      });
    });
  }

  function init() { var h = document.querySelector('[data-kb-surface="catalog"]'); if (h) mount(h); }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init); else init();
  global.KBCatalog = { mount: mount };
})(window);
